/* eslint quotes: 0, no-unused-vars: 0 */
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	"A description is required!": {
		"en": "A description is required!",
		"de": "Eine Beschreibung ist erforderlich!",
		"ru": "Описание обязательно!",
		"pt": "Uma descrição é obrigatória!",
		"nl": "Een beschrijving is verplicht!",
		"fr": "Une description est requise!",
		"it": "Necessita una descrizione!",
		"es": "Se requiere una descripción!",
		"pl": "Wymagany jest opis!",
		"zh-cn": "需要说明！"
	},
	"grpup_valve": {
		"en": "Valve",
		"de": "Ventil",
		"ru": "Клапан",
		"pt": "Válvula",
		"nl": "Klep",
		"fr": "Soupape",
		"it": "Valvola",
		"es": "Válvula",
		"pl": "Zawór",
		"zh-cn": "阀"
	},
	"picture": {
		"en": "picture",
		"de": "Bild",
		"ru": "рисунок",
		"pt": "cenário",
		"nl": "afbeelding",
		"fr": "image",
		"it": "immagine",
		"es": "imagen",
		"pl": "obrazek",
		"zh-cn": "图片"
	},
	"xpic": {
		"en": "left",
		"de": "links",
		"ru": "слева",
		"pt": "esquerda",
		"nl": "links",
		"fr": "la gauche",
		"it": "sinistra",
		"es": "izquierda",
		"pl": "lewo",
		"zh-cn": "剩下"
	},
	"ypic": {
		"en": "top",
		"de": "oben",
		"ru": "Топ",
		"pt": "topo",
		"nl": "top",
		"fr": "Haut",
		"it": "superiore",
		"es": "parte superior",
		"pl": "Top",
		"zh-cn": "最佳"
	},
	"wpic": {
		"en": "width",
		"de": "breite",
		"ru": "ширина",
		"pt": "largura",
		"nl": "breedte",
		"fr": "largeur",
		"it": "larghezza",
		"es": "anchura",
		"pl": "szerokość",
		"zh-cn": "宽度"
	},
	"hpic": {
		"en": "height",
		"de": "höhe",
		"ru": "высота",
		"pt": "altura",
		"nl": "hoogte",
		"fr": "la taille",
		"it": "altezza",
		"es": "altura",
		"pl": "wysokość",
		"zh-cn": "高度"
	},
	"atxt": {
		"en": "Roomname",
		"de": "Raumname",
		"ru": "Название комнаты",
		"pt": "Nome da sala",
		"nl": "Kamer naam",
		"fr": "Nom de la salle",
		"it": "Nome della stanza",
		"es": "Nombre de la habitación",
		"pl": "Nazwa pokoju",
		"zh-cn": "房间名称"
	},
	"title_oid": {
		"en": "room",
		"de": "Raum",
		"ru": "комната",
		"pt": "quarto",
		"nl": "kamer",
		"fr": "pièce",
		"it": "camera",
		"es": "habitación",
		"pl": "Pokój",
		"zh-cn": "房间"
	},
	"room": {
		"en": "room",
		"de": "Raum",
		"ru": "комната",
		"pt": "quarto",
		"nl": "kamer",
		"fr": "pièce",
		"it": "camera",
		"es": "habitación",
		"pl": "Pokój",
		"zh-cn": "房间"
	},
	"group_picture": {
		"en": "Picture",
		"de": "Bild",
		"ru": "Рисунок",
		"pt": "Cenário",
		"nl": "Afbeelding",
		"fr": "Image",
		"it": "Immagine",
		"es": "Imagen",
		"pl": "Obrazek",
		"zh-cn": "图片"
	},
	"xtxt": {
		"en": "left",
		"de": "links",
		"ru": "слева",
		"pt": "esquerda",
		"nl": "links",
		"fr": "la gauche",
		"it": "sinistra",
		"es": "izquierda",
		"pl": "lewo",
		"zh-cn": "剩下"
	},
	"ytxt": {
		"en": "top",
		"de": "oben",
		"ru": "Топ",
		"pt": "topo",
		"nl": "top",
		"fr": "Haut",
		"it": "superiore",
		"es": "parte superior",
		"pl": "Top",
		"zh-cn": "最佳"
	},
	"valveact": {
		"en": "Valve temperature",
		"de": "Ventiltemperatur",
		"ru": "Температура клапана",
		"pt": "Temperatura da válvula",
		"nl": "Kleptemperatuur",
		"fr": "Température de la vanne",
		"it": "Temperatura della valvola",
		"es": "Temperatura de la válvula",
		"pl": "Temperatura zaworu",
		"zh-cn": "阀门温度"
	},
	"valvesoll": {
		"en": "Target temperature",
		"de": "Solltemperatur",
		"ru": "Целевая температура",
		"pt": "Temperatura alvo",
		"nl": "Gewenste temperatuur",
		"fr": "Température cible",
		"it": "Temperatura target",
		"es": "Temperatura objetivo",
		"pl": "Temperatura docelowa",
		"zh-cn": "目标温度"
	},
	"valveist": {
		"en": "Actual temperature",
		"de": "Tatsächliche Temperatur",
		"ru": "Фактическая температура",
		"pt": "Temperatura real",
		"nl": "Werkelijke temperatuur",
		"fr": "Température réelle",
		"it": "Temperatura effettiva",
		"es": "Temperatura real",
		"pl": "Rzeczywista temperatura",
		"zh-cn": "实际温度"
	},
	"temp_oid": {
		"en": "Actual temperature",
		"de": "Tatsächliche Temperatur",
		"ru": "Фактическая температура",
		"pt": "Temperatura real",
		"nl": "Werkelijke temperatuur",
		"fr": "Température réelle",
		"it": "Temperatura effettiva",
		"es": "Temperatura real",
		"pl": "Rzeczywista temperatura",
		"zh-cn": "实际温度"
	},
	"act_oid": {
		"en": "Valve temperature",
		"de": "Ventiltemperatur",
		"ru": "Температура клапана",
		"pt": "Temperatura da válvula",
		"nl": "Kleptemperatuur",
		"fr": "Température de la vanne",
		"it": "Temperatura della valvola",
		"es": "Temperatura de la válvula",
		"pl": "Temperatura zaworu",
		"zh-cn": "阀门温度"
	},
	"ctxt": {
		"en": "textcolor",
		"de": "Textfarbe",
		"ru": "цвет текста",
		"pt": "cor do texto",
		"nl": "tekst kleur",
		"fr": "couleur du texte",
		"it": "colore del testo",
		"es": "color de texto",
		"pl": "kolor tekstu",
		"zh-cn": "文字颜色"
	},
	"catxt": {
		"en": "textcolor",
		"de": "Textfarbe",
		"ru": "цвет текста",
		"pt": "cor do texto",
		"nl": "tekst kleur",
		"fr": "couleur du texte",
		"it": "colore del testo",
		"es": "color de texto",
		"pl": "kolor tekstu",
		"zh-cn": "文字颜色"
	},
	"cstxt": {
		"en": "textcolor",
		"de": "Textfarbe",
		"ru": "цвет текста",
		"pt": "cor do texto",
		"nl": "tekst kleur",
		"fr": "couleur du texte",
		"it": "colore del testo",
		"es": "color de texto",
		"pl": "kolor tekstu",
		"zh-cn": "文字颜色"
	},
	"citxt": {
		"en": "textcolor",
		"de": "Textfarbe",
		"ru": "цвет текста",
		"pt": "cor do texto",
		"nl": "tekst kleur",
		"fr": "couleur du texte",
		"it": "colore del testo",
		"es": "color de texto",
		"pl": "kolor tekstu",
		"zh-cn": "文字颜色"
	},
	"group_temp": {
		"en": "Show temperature",
		"de": "Temperatur anzeigen",
		"ru": "Показать температуру",
		"pt": "Mostrar temperatura",
		"nl": "Toon temperatuur",
		"fr": "Afficher la température",
		"it": "Mostra la temperatura",
		"es": "Mostrar temperatura",
		"pl": "Pokaż temperaturę",
		"zh-cn": "显示温度"
	},
	"ctoparea": {
		"en": "Top area",
		"de": "Oberer Bereich",
		"ru": "Верхняя область",
		"pt": "Área superior",
		"nl": "Bovenste gedeelte",
		"fr": "Zone supérieure",
		"it": "Zona superiore",
		"es": "Zona superior",
		"pl": "Górny obszar",
		"zh-cn": "顶部区域"
	},
	"cbottomarea": {
		"en": "Bottom area",
		"de": "Unterer Bereich",
		"ru": "Нижняя область",
		"pt": "Área inferior",
		"nl": "Onderste gedeelte",
		"fr": "Zone inférieure",
		"it": "Area inferiore",
		"es": "Zona inferior",
		"pl": "Dolny obszar",
		"zh-cn": "底部区域"
	},
	"brltop": {
		"en": "Radius top / left",
		"de": "Radius oben / links",
		"ru": "Радиус вверху / слева",
		"pt": "Raio superior / esquerdo",
		"nl": "Straal boven / links",
		"fr": "Rayon haut / gauche",
		"it": "Raggio in alto / a sinistra",
		"es": "Radio arriba / izquierda",
		"pl": "Promień góra / lewo",
		"zh-cn": "半径上/左"
	},
	"brrtop": {
		"en": "Radius top / right",
		"de": "Radius oben / rechts",
		"ru": "Радиус вверху / справа",
		"pt": "Raio superior / direito",
		"nl": "Straal boven / rechts",
		"fr": "Rayon haut / droite",
		"it": "Raggio in alto / a destra",
		"es": "Radio arriba / derecha",
		"pl": "Promień góra / prawo",
		"zh-cn": "半径上/右"
	},
	"brlbottom": {
		"en": "Radius bottom / left",
		"de": "Radius unten / links",
		"ru": "Радиус внизу / слева",
		"pt": "Raio inferior / esquerdo",
		"nl": "Straal onder / links",
		"fr": "Rayon bas / gauche",
		"it": "Raggio in basso / sinistra",
		"es": "Radio abajo / izquierda",
		"pl": "Promień dół / lewo",
		"zh-cn": "半径底/左"
	},
	"brrbottom": {
		"en": "Radius bottom / right",
		"de": "Radius unten / rechts",
		"ru": "Радиус внизу / справа",
		"pt": "Raio inferior / direito",
		"nl": "Straal onder / rechts",
		"fr": "Rayon bas / droite",
		"it": "Raggio in basso / a destra",
		"es": "Radio abajo / derecha",
		"pl": "Promień dół / prawo",
		"zh-cn": "半径底/右"
	},
	"group_frame": {
		"en": "Design",
		"de": "Design",
		"ru": "дизайн",
		"pt": "Projeto",
		"nl": "Ontwerp",
		"fr": "Conception",
		"it": "Design",
		"es": "Diseño",
		"pl": "Projekt",
		"zh-cn": "设计"
	},
	"group_slider": {
		"en": "Slider",
		"de": "Schieberegler",
		"ru": "Слайдер",
		"pt": "Slider",
		"nl": "Schuifregelaar",
		"fr": "Glissière",
		"it": "Slider",
		"es": "Deslizador",
		"pl": "Suwak",
		"zh-cn": "滑杆"
	},
	"min": {
		"en": "minimum",
		"de": "Minimum",
		"ru": "минимум",
		"pt": "mínimo",
		"nl": "minimum",
		"fr": "le minimum",
		"it": "minimo",
		"es": "mínimo",
		"pl": "minimum",
		"zh-cn": "最低"
	},
	"max": {
		"en": "maximum",
		"de": "maximal",
		"ru": "максимум",
		"pt": "máximo",
		"nl": "maximum",
		"fr": "maximum",
		"it": "massimo",
		"es": "máximo",
		"pl": "maksymalny",
		"zh-cn": "最大"
	},
	"slider_oid": {
		"en": "Working area",
		"de": "Arbeitsbereich",
		"ru": "Рабочая область",
		"pt": "Área de trabalho",
		"nl": "Werkgebied",
		"fr": "Zone de travail",
		"it": "Area di lavoro",
		"es": "Área de trabajo",
		"pl": "Obszar roboczy",
		"zh-cn": "工作区域"
	},
	"step": {
		"en": "step",
		"de": "Schritt",
		"ru": "шаг",
		"pt": "degrau",
		"nl": "stap",
		"fr": "étape",
		"it": "passo",
		"es": "paso",
		"pl": "krok",
		"zh-cn": "步"
	},
	"orientation": {
		"en": "orientation",
		"de": "Orientierung",
		"ru": "ориентация",
		"pt": "orientação",
		"nl": "oriëntatie",
		"fr": "orientation",
		"it": "orientamento",
		"es": "orientación",
		"pl": "orientacja",
		"zh-cn": "方向"
	},
	"inverted": {
		"en": "inverted",
		"de": "invertiert",
		"ru": "перевернутый",
		"pt": "invertido",
		"nl": "omgekeerd",
		"fr": "inversé",
		"it": "invertito",
		"es": "invertido",
		"pl": "odwrotny",
		"zh-cn": "倒"
	},
	"submitmethod": {
		"en": "submitmethod",
		"de": "Submit-Methode",
		"ru": "submitmethod",
		"pt": "método de envio",
		"nl": "verzendmethode",
		"fr": "soumettre la méthode",
		"it": "submitmethod",
		"es": "método de envío",
		"pl": "submitmethod",
		"zh-cn": "提交方法"
	},
	"valveactbehind": {
		"en": "add behind",
		"de": "hinten hinzufügen",
		"ru": "добавить позади",
		"pt": "adicionar atrás",
		"nl": "achter toevoegen",
		"fr": "ajouter derrière",
		"it": "aggiungi dietro",
		"es": "agregar detrás",
		"pl": "dodaj za",
		"zh-cn": "加在后面"
	},
	"valvesollbehind": {
		"en": "add behind",
		"de": "hinten hinzufügen",
		"ru": "добавить позади",
		"pt": "adicionar atrás",
		"nl": "achter toevoegen",
		"fr": "ajouter derrière",
		"it": "aggiungi dietro",
		"es": "agregar detrás",
		"pl": "dodaj za",
		"zh-cn": "加在后面"
	},
	"valveistbehind": {
		"en": "add behind",
		"de": "hinten hinzufügen",
		"ru": "добавить позади",
		"pt": "adicionar atrás",
		"nl": "achter toevoegen",
		"fr": "ajouter derrière",
		"it": "aggiungi dietro",
		"es": "agregar detrás",
		"pl": "dodaj za",
		"zh-cn": "加在后面"
	},
	"topvalve": {
		"en": "top",
		"de": "oben",
		"ru": "Топ",
		"pt": "topo",
		"nl": "top",
		"fr": "Haut",
		"it": "superiore",
		"es": "parte superior",
		"pl": "Top",
		"zh-cn": "最佳"
	},
	"leftvalve": {
		"en": "left",
		"de": "links",
		"ru": "слева",
		"pt": "esquerda",
		"nl": "links",
		"fr": "la gauche",
		"it": "sinistra",
		"es": "izquierda",
		"pl": "lewo",
		"zh-cn": "剩下"
	},
	"topslider": {
		"en": "top",
		"de": "oben",
		"ru": "Топ",
		"pt": "topo",
		"nl": "top",
		"fr": "Haut",
		"it": "superiore",
		"es": "parte superior",
		"pl": "Top",
		"zh-cn": "最佳"
	},
	"leftslider": {
		"en": "left",
		"de": "links",
		"ru": "слева",
		"pt": "esquerda",
		"nl": "links",
		"fr": "la gauche",
		"it": "sinistra",
		"es": "izquierda",
		"pl": "lewo",
		"zh-cn": "剩下"
	},
	"widthslider": {
		"en": "width",
		"de": "breite",
		"ru": "ширина",
		"pt": "largura",
		"nl": "breedte",
		"fr": "largeur",
		"it": "larghezza",
		"es": "anchura",
		"pl": "szerokość",
		"zh-cn": "宽度"
	},
	"tempfont": {
		"en": "Fontname",
		"de": "Schriftartenname",
		"ru": "Название шрифта",
		"pt": "Nome da fonte",
		"nl": "Lettertype",
		"fr": "Nom de la police",
		"it": "Nome carattere",
		"es": "Nombre de la fuente",
		"pl": "Nazwa czcionki",
		"zh-cn": "字体名称"
	},
	"tempfontsize": {
		"en": "fontsize",
		"de": "Schriftgröße",
		"ru": "размер шрифта",
		"pt": "tamanho da fonte",
		"nl": "lettertypegrootte",
		"fr": "taille de police",
		"it": "dimensione del font",
		"es": "tamaño de fuente",
		"pl": "rozmiar czcionki",
		"zh-cn": "字体大小"
	},
	"txtfont": {
		"en": "Fontname",
		"de": "Schriftartenname",
		"ru": "Название шрифта",
		"pt": "Nome da fonte",
		"nl": "Lettertype",
		"fr": "Nom de la police",
		"it": "Nome carattere",
		"es": "Nombre de la fuente",
		"pl": "Nazwa czcionki",
		"zh-cn": "字体名称"
	},
	"txtfontsize": {
		"en": "fontsize",
		"de": "Schriftgröße",
		"ru": "размер шрифта",
		"pt": "tamanho da fonte",
		"nl": "lettertypegrootte",
		"fr": "taille de police",
		"it": "dimensione del font",
		"es": "tamaño de fuente",
		"pl": "rozmiar czcionki",
		"zh-cn": "字体大小"
	},
	"upd_oid": {
		"en": "Update API",
		"de": "API aktualisieren",
		"ru": "Обновить API",
		"pt": "API de atualização",
		"nl": "Update API",
		"fr": "Mettre à jour l'API",
		"it": "Aggiorna API",
		"es": "Actualizar API",
		"pl": "Zaktualizuj API",
		"zh-cn": "更新API"
	},
	"show_win": {
		"en": "Show window open sign",
		"de": "zeige 'Fenster offen'",
		"ru": "Показать знак открытого окна",
		"pt": "Mostrar sinal de janela aberta",
		"nl": "Toon venster open teken",
		"fr": "Afficher le signe d'ouverture de la fenêtre",
		"it": "Mostra il segno di finestra aperta",
		"es": "Mostrar signo de ventana abierta",
		"pl": "Pokaż znak otwartego okna",
		"zh-cn": "显示窗口打开标志"
	}
};
