/* eslint quotes: 0, no-unused-vars: 0 */
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'A description is required!': {
		en: 'A description is required!',
		de: 'Eine Beschreibung ist erforderlich!',
		ru: 'Описание обязательно!',
		pt: 'Uma descrição é obrigatória!',
		nl: 'Een beschrijving is verplicht!',
		fr: 'Une description est requise!',
		it: 'Necessita una descrizione!',
		es: 'Se requiere una descripción!',
		pl: 'Wymagany jest opis!',
		'zh-cn': '需要说明！',
	},
	oid: {
		en: 'SetTemp datapoint',
		de: 'SetTemp Datenpunkt',
		ru: 'SetTemp датапоинт',
		pt: 'Ponto de dados SetTemp',
		nl: 'SetTemp datapunt',
		fr: 'Point de données SetTemp',
		it: 'SetTemp datapoint',
		es: 'Punto de datos SetTemp',
		pl: 'Punkt danych SetTemp',
		'zh-cn': 'SetTemp数据点',
	},
	grpup_valve: {
		en: 'Valve',
		de: 'Ventil',
		ru: 'Клапан',
		pt: 'Válvula',
		nl: 'Klep',
		fr: 'Soupape',
		it: 'Valvola',
		es: 'Válvula',
		pl: 'Zawór',
		'zh-cn': '阀',
	},
	group_signals_widget: {
		en: 'Warnings',
		de: 'Warnungen',
		ru: 'Предупреждения',
		pt: 'Avisos',
		nl: 'Waarschuwingen',
		fr: 'Mises en garde',
		it: 'Avvertenze',
		es: 'Advertencias',
		pl: 'Ostrzeżenia',
		'zh-cn': '警告事项',
	},
	pic_running: {
		en: 'active now',
		de: 'jetzt aktiv',
		ru: 'в данный момент активен',
		pt: 'ativo agora',
		nl: 'nu actief',
		fr: 'actif maintenant',
		it: 'attivo ora',
		es: 'activo ahora',
		pl: 'aktywne teraz',
		'zh-cn': '现在激活',
	},
	xpos_running: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	ypos_running: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	size_running: {
		en: 'Size',
		de: 'Größe',
		ru: 'Размер',
		pt: 'Tamanho',
		nl: 'Grootte',
		fr: 'Taille',
		it: 'Taglia',
		es: 'Talla',
		pl: 'Rozmiar',
		'zh-cn': '尺寸',
	},
	refr_oid: {
		en: 'Refresh structure',
		de: 'Struktur aktualisieren',
		ru: 'Обновить структуру',
		pt: 'Atualizar estrutura',
		nl: 'Vernieuw de structuur',
		fr: 'Actualiser la structure',
		it: 'Aggiorna la struttura',
		es: 'Actualizar estructura',
		pl: 'Odśwież strukturę',
		'zh-cn': '刷新结构',
	},
	show_refresh: {
		en: 'Show refresh',
		de: 'Aktualisierung anzeigen',
		ru: 'Показать обновить',
		pt: 'Mostrar atualização',
		nl: 'Toon vernieuwen',
		fr: 'Afficher le rafraîchissement',
		it: 'Mostra aggiornamento',
		es: 'Mostrar actualización',
		pl: 'Pokaż odśwież',
		'zh-cn': '显示刷新',
	},
	pic_refresh: {
		en: 'refresh',
		de: 'Aktualisierung',
		ru: 'обновить',
		pt: 'refrescar',
		nl: 'vernieuwen',
		fr: 'rafraîchir',
		it: 'ricaricare',
		es: 'actualizar',
		pl: 'odświeżać',
		'zh-cn': '刷新',
	},
	xpos_refresh: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	ypos_refresh: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	size_refresh: {
		en: 'Size',
		de: 'Größe',
		ru: 'Размер',
		pt: 'Tamanho',
		nl: 'Grootte',
		fr: 'Taille',
		it: 'Taglia',
		es: 'Talla',
		pl: 'Rozmiar',
		'zh-cn': '尺寸',
	},
	show_logo: {
		en: 'Show Logo',
		de: 'Logo anzeigen',
		ru: 'Показать логотип',
		pt: 'Mostrar logotipo',
		nl: 'Logo weergeven',
		fr: 'Afficher le logo',
		it: 'Mostra logo',
		es: 'Mostrar logotipo',
		pl: 'Pokaż logo',
		'zh-cn': '显示徽标',
	},
	pic_logo: {
		en: 'Logo',
		de: 'Logo',
		ru: 'Логотип',
		pt: 'Logotipo',
		nl: 'Logo',
		fr: 'Logo',
		it: 'Logo',
		es: 'Logo',
		pl: 'Logo',
		'zh-cn': '商标',
	},
	xpos_logo: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	ypos_logo: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	size_logo: {
		en: 'Size',
		de: 'Größe',
		ru: 'Размер',
		pt: 'Tamanho',
		nl: 'Grootte',
		fr: 'Taille',
		it: 'Taglia',
		es: 'Talla',
		pl: 'Rozmiar',
		'zh-cn': '尺寸',
	},
	show_windowopen: {
		en: "Show 'open window'",
		de: "'Fenster geöffnet' anzeigen",
		ru: "Показать 'открытое окно'",
		pt: "Mostrar 'janela aberta'",
		nl: "Toon 'open venster'",
		fr: "Afficher 'fenêtre ouverte'",
		it: "Mostra 'finestra aperta'",
		es: "Mostrar 'ventana abierta'",
		pl: 'Pokaż „otwarte okno”',
		'zh-cn': '显示“打开的窗口”',
	},
	pic_windowopen: {
		en: 'Window open',
		de: 'Fenster offen',
		ru: 'Окно открыто',
		pt: 'Janela aberta',
		nl: 'Venster open',
		fr: 'Fenêtre ouverte',
		it: 'Finestra aperta',
		es: 'Ventana abierta',
		pl: 'Okno otwarte',
		'zh-cn': '开窗',
	},
	xpos_window: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	ypos_window: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	size_window: {
		en: 'Size',
		de: 'Größe',
		ru: 'Размер',
		pt: 'Tamanho',
		nl: 'Grootte',
		fr: 'Taille',
		it: 'Taglia',
		es: 'Talla',
		pl: 'Rozmiar',
		'zh-cn': '尺寸',
	},
	show_reachable: {
		en: "Show 'reachable'",
		de: "'erreichbar' anzeigen",
		ru: "Показать 'достижимо'",
		pt: "Mostrar 'alcançável'",
		nl: "Toon 'bereikbaar'",
		fr: 'Afficher «accessible»',
		it: "Mostra 'raggiungibile'",
		es: "Mostrar 'accesible'",
		pl: 'Pokaż „osiągalny”',
		'zh-cn': '显示“可达”',
	},
	pic_reachable: {
		en: 'reachable',
		de: 'Verbunden',
		ru: 'достижимый',
		pt: 'alcançável',
		nl: 'bereikbaar',
		fr: 'accessible',
		it: 'raggiungibile',
		es: 'accesible',
		pl: 'osiągalny',
		'zh-cn': '可达的',
	},
	xpos_reachable: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	ypos_reachable: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	size_reachhable: {
		en: 'Size',
		de: 'Größe',
		ru: 'Размер',
		pt: 'Tamanho',
		nl: 'Grootte',
		fr: 'Taille',
		it: 'Taglia',
		es: 'Talla',
		pl: 'Rozmiar',
		'zh-cn': '尺寸',
	},
	show_anticipating: {
		en: "Show 'anticipating'",
		de: "'antizipieren' anzeigen",
		ru: "Шоу 'предвкушение'",
		pt: "Mostrar 'antecipação'",
		nl: "Toon 'anticiperen'",
		fr: "Montrer 'anticiper'",
		it: "Mostra 'anticipazione'",
		es: "Mostrar 'anticipando'",
		pl: 'Pokaż „przewidywanie”',
		'zh-cn': '显示“期待中”',
	},
	pic_anticipating: {
		en: 'anticipating',
		de: 'Antizipation',
		ru: 'ожидание',
		pt: 'antecipando',
		nl: 'anticiperen',
		fr: 'anticipant',
		it: 'anticipando',
		es: 'anticipando',
		pl: 'przewidywanie',
		'zh-cn': '期待的',
	},
	xpos_anticipating: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	ypos_anticipating: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	size_anticipating: {
		en: 'Size',
		de: 'Größe',
		ru: 'Размер',
		pt: 'Tamanho',
		nl: 'Grootte',
		fr: 'Taille',
		it: 'Taglia',
		es: 'Talla',
		pl: 'Rozmiar',
		'zh-cn': '尺寸',
	},
	alternativ_title: {
		en: 'Roomname',
		de: 'Raumname',
		ru: 'Название комнаты',
		pt: 'Nome da sala',
		nl: 'Kamer naam',
		fr: 'Nom de la salle',
		it: 'Nome della stanza',
		es: 'Nombre de la habitación',
		pl: 'Nazwa pokoju',
		'zh-cn': '房间名称',
	},
	title_oid: {
		en: 'room',
		de: 'Raum',
		ru: 'комната',
		pt: 'quarto',
		nl: 'kamer',
		fr: 'pièce',
		it: 'camera',
		es: 'habitación',
		pl: 'Pokój',
		'zh-cn': '房间',
	},
	room: {
		en: 'room',
		de: 'Raum',
		ru: 'комната',
		pt: 'quarto',
		nl: 'kamer',
		fr: 'pièce',
		it: 'camera',
		es: 'habitación',
		pl: 'Pokój',
		'zh-cn': '房间',
	},
	group_picture: {
		en: 'Logo & API ',
		de: 'Logo & API',
		ru: 'Логотип и API',
		pt: 'Logo e API',
		nl: 'Logo en API',
		fr: 'Logo et API',
		it: 'Logo e API',
		es: 'Logotipo y API',
		pl: 'Logo i API',
		'zh-cn': '徽标和API',
	},
	xpos_title: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	ypos_title: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	valve_now: {
		en: 'Valve temperature',
		de: 'Ventiltemperatur',
		ru: 'Температура клапана',
		pt: 'Temperatura da válvula',
		nl: 'Kleptemperatuur',
		fr: 'Température de la vanne',
		it: 'Temperatura della valvola',
		es: 'Temperatura de la válvula',
		pl: 'Temperatura zaworu',
		'zh-cn': '阀门温度',
	},
	valve_target: {
		en: 'Target temperature',
		de: 'Solltemperatur',
		ru: 'Целевая температура',
		pt: 'Temperatura alvo',
		nl: 'Gewenste temperatuur',
		fr: 'Température cible',
		it: 'Temperatura target',
		es: 'Temperatura objetivo',
		pl: 'Temperatura docelowa',
		'zh-cn': '目标温度',
	},
	valve_actual: {
		en: 'Actual temperature',
		de: 'Tatsächliche Temperatur',
		ru: 'Фактическая температура',
		pt: 'Temperatura real',
		nl: 'Werkelijke temperatuur',
		fr: 'Température réelle',
		it: 'Temperatura effettiva',
		es: 'Temperatura real',
		pl: 'Rzeczywista temperatura',
		'zh-cn': '实际温度',
	},
	temp_oid: {
		en: 'Actual temperature',
		de: 'Tatsächliche Temperatur',
		ru: 'Фактическая температура',
		pt: 'Temperatura real',
		nl: 'Werkelijke temperatuur',
		fr: 'Température réelle',
		it: 'Temperatura effettiva',
		es: 'Temperatura real',
		pl: 'Rzeczywista temperatura',
		'zh-cn': '实际温度',
	},
	act_oid: {
		en: 'Valve temperature',
		de: 'Ventiltemperatur',
		ru: 'Температура клапана',
		pt: 'Temperatura da válvula',
		nl: 'Kleptemperatuur',
		fr: 'Température de la vanne',
		it: 'Temperatura della valvola',
		es: 'Temperatura de la válvula',
		pl: 'Temperatura zaworu',
		'zh-cn': '阀门温度',
	},
	color_title: {
		en: 'textcolor',
		de: 'Textfarbe',
		ru: 'цвет текста',
		pt: 'cor do texto',
		nl: 'tekst kleur',
		fr: 'couleur du texte',
		it: 'colore del testo',
		es: 'color de texto',
		pl: 'kolor tekstu',
		'zh-cn': '文字颜色',
	},
	temperature_valve_color: {
		en: 'textcolor',
		de: 'Textfarbe',
		ru: 'цвет текста',
		pt: 'cor do texto',
		nl: 'tekst kleur',
		fr: 'couleur du texte',
		it: 'colore del testo',
		es: 'color de texto',
		pl: 'kolor tekstu',
		'zh-cn': '文字颜色',
	},
	temperature_target_color: {
		en: 'textcolor',
		de: 'Textfarbe',
		ru: 'цвет текста',
		pt: 'cor do texto',
		nl: 'tekst kleur',
		fr: 'couleur du texte',
		it: 'colore del testo',
		es: 'color de texto',
		pl: 'kolor tekstu',
		'zh-cn': '文字颜色',
	},
	temperature_ist_color: {
		en: 'textcolor',
		de: 'Textfarbe',
		ru: 'цвет текста',
		pt: 'cor do texto',
		nl: 'tekst kleur',
		fr: 'couleur du texte',
		it: 'colore del testo',
		es: 'color de texto',
		pl: 'kolor tekstu',
		'zh-cn': '文字颜色',
	},
	group_temp: {
		en: 'Show temperatures',
		de: 'Temperaturen anzeigen',
		ru: 'Показать температуры',
		pt: 'Mostrar temperaturas',
		nl: 'Toon temperaturen',
		fr: 'Afficher les températures',
		it: 'Mostra le temperature',
		es: 'Mostrar temperaturas',
		pl: 'Pokaż temperatury',
		'zh-cn': '显示温度',
	},
	frame_top_color: {
		en: 'Top area',
		de: 'Oberer Bereich',
		ru: 'Верхняя область',
		pt: 'Área superior',
		nl: 'Bovenste gedeelte',
		fr: 'Zone supérieure',
		it: 'Zona superiore',
		es: 'Zona superior',
		pl: 'Górny obszar',
		'zh-cn': '顶部区域',
	},
	frame_bottom_color: {
		en: 'Bottom area',
		de: 'Unterer Bereich',
		ru: 'Нижняя область',
		pt: 'Área inferior',
		nl: 'Onderste gedeelte',
		fr: 'Zone inférieure',
		it: 'Area inferiore',
		es: 'Zona inferior',
		pl: 'Dolny obszar',
		'zh-cn': '底部区域',
	},
	frame_left_top_radius: {
		en: 'Radius top / left',
		de: 'Radius oben / links',
		ru: 'Радиус вверху / слева',
		pt: 'Raio superior / esquerdo',
		nl: 'Straal boven / links',
		fr: 'Rayon haut / gauche',
		it: 'Raggio in alto / a sinistra',
		es: 'Radio arriba / izquierda',
		pl: 'Promień góra / lewo',
		'zh-cn': '半径上/左',
	},
	frame_rigth_top_radius: {
		en: 'Radius top / right',
		de: 'Radius oben / rechts',
		ru: 'Радиус вверху / справа',
		pt: 'Raio superior / direito',
		nl: 'Straal boven / rechts',
		fr: 'Rayon haut / droite',
		it: 'Raggio in alto / a destra',
		es: 'Radio arriba / derecha',
		pl: 'Promień góra / prawo',
		'zh-cn': '半径上/右',
	},
	frame_left_bottom_radius: {
		en: 'Radius bottom / left',
		de: 'Radius unten / links',
		ru: 'Радиус внизу / слева',
		pt: 'Raio inferior / esquerdo',
		nl: 'Straal onder / links',
		fr: 'Rayon bas / gauche',
		it: 'Raggio in basso / sinistra',
		es: 'Radio abajo / izquierda',
		pl: 'Promień dół / lewo',
		'zh-cn': '半径底/左',
	},
	frame_right_bottom_radius: {
		en: 'Radius bottom / right',
		de: 'Radius unten / rechts',
		ru: 'Радиус внизу / справа',
		pt: 'Raio inferior / direito',
		nl: 'Straal onder / rechts',
		fr: 'Rayon bas / droite',
		it: 'Raggio in basso / a destra',
		es: 'Radio abajo / derecha',
		pl: 'Promień dół / prawo',
		'zh-cn': '半径底/右',
	},
	group_frame: {
		en: 'Design',
		de: 'Design',
		ru: 'дизайн',
		pt: 'Projeto',
		nl: 'Ontwerp',
		fr: 'Conception',
		it: 'Design',
		es: 'Diseño',
		pl: 'Projekt',
		'zh-cn': '设计',
	},
	group_slider: {
		en: 'Temperature controller',
		de: 'Temperaturregler',
		ru: 'Регулятор температуры',
		pt: 'Controlador de temperatura',
		nl: 'Temperatuurregelaar',
		fr: 'Contrôleur de température',
		it: 'Regolatore di temperatura',
		es: 'Controlador de temperatura',
		pl: 'Kontroler temperatury',
		'zh-cn': '温度控制器',
	},
	min: {
		en: 'minimum',
		de: 'minimum',
		ru: 'минимум',
		pt: 'mínimo',
		nl: 'minimum',
		fr: 'le minimum',
		it: 'minimo',
		es: 'mínimo',
		pl: 'minimum',
		'zh-cn': '最低',
	},
	max: {
		en: 'maximum',
		de: 'maximum',
		ru: 'максимум',
		pt: 'máximo',
		nl: 'maximum',
		fr: 'maximum',
		it: 'massimo',
		es: 'máximo',
		pl: 'maksymalny',
		'zh-cn': '最大',
	},
	slider_oid: {
		en: 'Working area',
		de: 'Arbeitsbereich',
		ru: 'Рабочая область',
		pt: 'Área de trabalho',
		nl: 'Werkgebied',
		fr: 'Zone de travail',
		it: 'Area di lavoro',
		es: 'Área de trabajo',
		pl: 'Obszar roboczy',
		'zh-cn': '工作区域',
	},
	step: {
		en: 'step',
		de: 'Schritt',
		ru: 'шаг',
		pt: 'degrau',
		nl: 'stap',
		fr: 'étape',
		it: 'passo',
		es: 'paso',
		pl: 'krok',
		'zh-cn': '步',
	},
	orientation: {
		en: 'orientation',
		de: 'Orientierung',
		ru: 'ориентация',
		pt: 'orientação',
		nl: 'oriëntatie',
		fr: 'orientation',
		it: 'orientamento',
		es: 'orientación',
		pl: 'orientacja',
		'zh-cn': '方向',
	},
	inverted: {
		en: 'inverted',
		de: 'invertiert',
		ru: 'перевернутый',
		pt: 'invertido',
		nl: 'omgekeerd',
		fr: 'inversé',
		it: 'invertito',
		es: 'invertido',
		pl: 'odwrotny',
		'zh-cn': '倒',
	},
	submitmethod: {
		en: 'submitmethod',
		de: 'Submit-Methode',
		ru: 'submitmethod',
		pt: 'método de envio',
		nl: 'verzendmethode',
		fr: 'soumettre la méthode',
		it: 'submitmethod',
		es: 'método de envío',
		pl: 'submitmethod',
		'zh-cn': '提交方法',
	},
	valve_now_behind: {
		en: 'add behind',
		de: 'hinten hinzufügen',
		ru: 'добавить позади',
		pt: 'adicionar atrás',
		nl: 'achter toevoegen',
		fr: 'ajouter derrière',
		it: 'aggiungi dietro',
		es: 'agregar detrás',
		pl: 'dodaj za',
		'zh-cn': '加在后面',
	},
	valve_target_behind: {
		en: 'add behind',
		de: 'hinten hinzufügen',
		ru: 'добавить позади',
		pt: 'adicionar atrás',
		nl: 'achter toevoegen',
		fr: 'ajouter derrière',
		it: 'aggiungi dietro',
		es: 'agregar detrás',
		pl: 'dodaj za',
		'zh-cn': '加在后面',
	},
	valve_actual_behind: {
		en: 'add behind',
		de: 'hinten hinzufügen',
		ru: 'добавить позади',
		pt: 'adicionar atrás',
		nl: 'achter toevoegen',
		fr: 'ajouter derrière',
		it: 'aggiungi dietro',
		es: 'agregar detrás',
		pl: 'dodaj za',
		'zh-cn': '加在后面',
	},
	top_valve: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	left_valve: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	top_slider: {
		en: 'top',
		de: 'oben',
		ru: 'Топ',
		pt: 'topo',
		nl: 'top',
		fr: 'Haut',
		it: 'superiore',
		es: 'parte superior',
		pl: 'Top',
		'zh-cn': '最佳',
	},
	left_slider: {
		en: 'left',
		de: 'links',
		ru: 'слева',
		pt: 'esquerda',
		nl: 'links',
		fr: 'la gauche',
		it: 'sinistra',
		es: 'izquierda',
		pl: 'lewo',
		'zh-cn': '剩下',
	},
	width_slider: {
		en: 'width',
		de: 'breite',
		ru: 'ширина',
		pt: 'largura',
		nl: 'breedte',
		fr: 'largeur',
		it: 'larghezza',
		es: 'anchura',
		pl: 'szerokość',
		'zh-cn': '宽度',
	},
	temperature_font: {
		en: 'Fontname',
		de: 'Schriftart',
		ru: 'Название шрифта',
		pt: 'Nome da fonte',
		nl: 'Lettertype',
		fr: 'Nom de la police',
		it: 'Nome carattere',
		es: 'Nombre de la fuente',
		pl: 'Nazwa czcionki',
		'zh-cn': '字体名称',
	},
	temperature_fontsize: {
		en: 'fontsize',
		de: 'Schriftgröße',
		ru: 'размер шрифта',
		pt: 'tamanho da fonte',
		nl: 'lettertypegrootte',
		fr: 'taille de police',
		it: 'dimensione del font',
		es: 'tamaño de fuente',
		pl: 'rozmiar czcionki',
		'zh-cn': '字体大小',
	},
	title_font: {
		en: 'Fontname',
		de: 'Schriftartenname',
		ru: 'Название шрифта',
		pt: 'Nome da fonte',
		nl: 'Lettertype',
		fr: 'Nom de la police',
		it: 'Nome carattere',
		es: 'Nombre de la fuente',
		pl: 'Nazwa czcionki',
		'zh-cn': '字体名称',
	},
	title_fontsize: {
		en: 'fontsize',
		de: 'Schriftgröße',
		ru: 'размер шрифта',
		pt: 'tamanho da fonte',
		nl: 'lettertypegrootte',
		fr: 'taille de police',
		it: 'dimensione del font',
		es: 'tamaño de fuente',
		pl: 'rozmiar czcionki',
		'zh-cn': '字体大小',
	},
	upd_oid: {
		en: 'Update API',
		de: 'API aktualisieren',
		ru: 'Обновить API',
		pt: 'API de atualização',
		nl: 'Update API',
		fr: "Mettre à jour l'API",
		it: 'Aggiorna API',
		es: 'Actualizar API',
		pl: 'Zaktualizuj API',
		'zh-cn': '更新API',
	},
	position_target: {
		en: 'Line number',
		de: 'Zeilennummer',
		ru: 'Номер строчки',
		pt: 'Número da linha',
		nl: 'Regelnummer',
		fr: 'Numéro de ligne',
		it: 'Numero di riga',
		es: 'Número de línea',
		pl: 'Numer kolejki',
		'zh-cn': '电话号码',
	},
	position_actual: {
		en: 'Line number',
		de: 'Zeilennummer',
		ru: 'Номер строчки',
		pt: 'Número da linha',
		nl: 'Regelnummer',
		fr: 'Numéro de ligne',
		it: 'Numero di riga',
		es: 'Número de línea',
		pl: 'Numer kolejki',
		'zh-cn': '电话号码',
	},
	position_now: {
		en: 'Line number',
		de: 'Zeilennummer',
		ru: 'Номер строчки',
		pt: 'Número da linha',
		nl: 'Regelnummer',
		fr: 'Numéro de ligne',
		it: 'Numero di riga',
		es: 'Número de línea',
		pl: 'Numer kolejki',
		'zh-cn': '电话号码',
	},
};
