/* eslint quotes: 0, no-unused-vars: 0 */
/*global systemDictionary:true */
'use strict';

const _systemDictionary = {
	"netatmo-energy adapter settings": {
		"en": "Adapter settings for netatmo-energy",
		"de": "Adaptereinstellungen für netatmo-energy",
		"ru": "Настройки адаптера для netatmo-energy",
		"pt": "Configurações do adaptador para netatmo-energy",
		"nl": "Adapterinstellingen voor netatmo-energy",
		"fr": "Paramètres d'adaptateur pour netatmo-energy",
		"it": "Impostazioni dell adattatore per netatmo-energy",
		"es": "Ajustes del adaptador para netatmo-energy",
		"pl": "Ustawienia adaptera dla netatmo-energy",
		"zh-cn": "netatmo-energy的适配器设置"
	},
	"Home-ID:": {
		"en": "Home-ID:",
		"de": "Home-ID:",
		"ru": "Домашний ID:",
		"pt": "ID de casa:",
		"nl": "Huis-ID:",
		"fr": "Identifiant du domicile:",
		"it": "ID casa:",
		"es": "ID de casa:",
		"pl": "Home-ID:",
		"zh-cn": "家庭ID："
	},
	"Client-ID:": {
		"en": "Client-ID:",
		"de": "Client-ID:",
		"ru": "ID клиента:",
		"pt": "ID do Cliente:",
		"nl": "Klant identificatie:",
		"fr": "Identité du client:",
		"it": "Identificativo cliente:",
		"es": "Identificación del cliente:",
		"pl": "Identyfikator klienta:",
		"zh-cn": "客户编号："
	},
	"Client-Secret-ID:": {
		"en": "Client-Secret-ID:",
		"de": "Client-Secret-ID:",
		"ru": "Client-Secret-ID:",
		"pt": "Client-Secret-ID:",
		"nl": "Client-geheim-ID:",
		"fr": "Client-Secret-ID:",
		"it": "ID segreto client:",
		"es": "ID secreto del cliente:",
		"pl": "Client-Secret-ID:",
		"zh-cn": "客户机密ID："
	},
	"Username:": {
		"en": "Username:",
		"de": "Benutzername:",
		"ru": "Имя пользователя:",
		"pt": "Nome do usuário:",
		"nl": "Gebruikersnaam:",
		"fr": "Nom d'utilisateur:",
		"it": "Nome utente:",
		"es": "Nombre de usuario:",
		"pl": "Nazwa Użytkownika:",
		"zh-cn": "用户名:"
	},
	"Password:": {
		"en": "Password:",
		"de": "Passwort:",
		"ru": "Пароль:",
		"pt": "Senha:",
		"nl": "Wachtwoord:",
		"fr": "Mot de passe:",
		"it": "Parola d'ordine:",
		"es": "Contraseña:",
		"pl": "Hasło:",
		"zh-cn": "密码："
	},
	"Home ID from your Netatmo Energy installation": {
		"en": "Home ID from your Netatmo Energy installation",
		"de": "Home ID von Ihrer Netatmo Energy-Installation",
		"ru": "Домашний идентификатор из вашей установки Netatmo Energy",
		"pt": "Home ID da sua instalação Netatmo Energy",
		"nl": "Home ID van uw Netatmo Energy-installatie",
		"fr": "Identifiant du domicile de votre installation Netatmo Energy",
		"it": "ID casa dalla tua installazione Netatmo Energy",
		"es": "Home ID de su instalación de Netatmo Energy",
		"pl": "Identyfikator domu z instalacji Netatmo Energy",
		"zh-cn": "Netatmo Energy安装中的家庭ID"
	},
	"Client ID from your Netatmo APP": {
		"en": "Client ID from your Netatmo APP",
		"de": "Client ID von ihrer Netatmo APP",
		"ru": "Идентификатор клиента из вашего приложения Netatmo",
		"pt": "ID de cliente de seu aplicativo Netatmo",
		"nl": "Client-ID van uw Netatmo-app",
		"fr": "ID client de votre APP Netatmo",
		"it": "ID client dalla tua APP Netatmo",
		"es": "ID de cliente de su aplicación Netatmo",
		"pl": "Identyfikator klienta z aplikacji Netatmo",
		"zh-cn": "来自Netatmo APP的客户端ID"
	},
	"Client Secret ID from your Netatmo APP": {
		"en": "Client Secret ID from your Netatmo APP",
		"de": "Client Secret ID von ihrer Netatmo APP",
		"ru": "Идентификатор секрета клиента из вашего приложения Netatmo",
		"pt": "ID secreta do cliente de seu aplicativo Netatmo",
		"nl": "Client Secret ID van uw Netatmo APP",
		"fr": "Identifiant secret client de votre application Netatmo",
		"it": "ID segreto client dalla tua APP Netatmo",
		"es": "ID secreto del cliente de su aplicación Netatmo",
		"pl": "Tajny identyfikator klienta z aplikacji Netatmo",
		"zh-cn": "来自Netatmo APP的客户端密钥ID"
	},
	"Username from your Netatmo Account": {
		"en": "Username from your Netatmo Account",
		"de": "Benutzername von ihrem Netatmo-Konto",
		"ru": "Имя пользователя из вашей учетной записи Netatmo",
		"pt": "Nome de usuário da sua conta Netatmo",
		"nl": "Gebruikersnaam van uw Netatmo-account",
		"fr": "Nom d'utilisateur de votre compte Netatmo",
		"it": "Nome utente dal tuo account Netatmo",
		"es": "Nombre de usuario de su cuenta Netatmo",
		"pl": "Nazwa użytkownika z konta Netatmo",
		"zh-cn": "您的Netatmo帐户的用户名"
	},
	"Password from your Netatmo Account": {
		"en": "Password from your Netatmo Account",
		"de": "Passwort von ihrem Netatmo-Konto",
		"ru": "Пароль от вашей учетной записи Netatmo",
		"pt": "Senha da sua conta Netatmo",
		"nl": "Wachtwoord van uw Netatmo-account",
		"fr": "Mot de passe de votre compte Netatmo",
		"it": "Password dal tuo account Netatmo",
		"es": "Contraseña de su cuenta Netatmo",
		"pl": "Hasło z Twojego konta Netatmo",
		"zh-cn": "您的Netatmo帐户的密码"
	},
	"General settings": {
		"en": "General settings",
		"de": "Allgemeine Einstellungen",
		"ru": "Общие настройки",
		"pt": "Configurações Gerais",
		"nl": "Algemene instellingen",
		"fr": "Réglages généraux",
		"it": "Impostazioni generali",
		"es": "Configuración general",
		"pl": "Ustawienia główne",
		"zh-cn": "常规设置"
	},
	"apply immediately": {
		"en": "apply temperature immediately",
		"de": "Temperaturänderung sofort übertragen",
		"ru": "немедленно применить температуру",
		"pt": "aplique a temperatura imediatamente",
		"nl": "breng de temperatuur onmiddellijk aan",
		"fr": "appliquer la température immédiatement",
		"it": "applicare immediatamente la temperatura",
		"es": "aplicar temperatura inmediatamente",
		"pl": "natychmiast zastosować temperaturę",
		"zh-cn": "立即施加温度"
	},
	"read API states immediately": {
		"en": "read API states immediately",
		"de": "API-Zustände nach Änderung sofort lesen",
		"ru": "немедленно читать состояния API",
		"pt": "leia os estados da API imediatamente",
		"nl": "lees API-staten onmiddellijk",
		"fr": "lire les états de l'API immédiatement",
		"it": "leggere immediatamente gli stati dell'API",
		"es": "leer los estados de la API inmediatamente",
		"pl": "natychmiast odczytaj stany API",
		"zh-cn": "立即读取API状态"
	},
	"refresh states after (sec):": {
		"en": "refresh states after (sec):",
		"de": "Aktualisierungszustände nach (Sek.):",
		"ru": "обновить состояния через (сек):",
		"pt": "atualizar estados após (segundos):",
		"nl": "verversingsstatussen na (sec):",
		"fr": "rafraîchir les états après (sec):",
		"it": "stati di aggiornamento dopo (sec):",
		"es": "actualizar estados después (seg):",
		"pl": "odśwież stany po (sek.):",
		"zh-cn": "在（秒）后刷新状态："
	},
	"Logon information": {
		"en": "Logon information",
		"de": "Anmeldeinformationen",
		"ru": "Информация для входа",
		"pt": "Informação de logon",
		"nl": "Aanmeldingsgegevens",
		"fr": "Informations de connexion",
		"it": "Informazioni di accesso",
		"es": "Información de inicio de sesión",
		"pl": "Informacje logowania",
		"zh-cn": "登录信息"
	},
	"API settings": {
		"en": "API settings",
		"de": "API-Einstellungen",
		"ru": "Настройки API",
		"pt": "Configurações de API",
		"nl": "API-instellingen",
		"fr": "Paramètres de l'API",
		"it": "Impostazioni API",
		"es": "Configuración de API",
		"pl": "Ustawienia API",
		"zh-cn": "API设定"
	},
	"Refresh states every x seconds": {
		"en": "Refresh states every x seconds",
		"de": "Aktualisierung der API-States alle x Sekunden",
		"ru": "Обновлять состояния каждые x секунд",
		"pt": "Atualizar estados a cada x segundos",
		"nl": "Vernieuwingsstatussen elke x seconden",
		"fr": "Actualiser les états toutes les x secondes",
		"it": "Aggiorna stati ogni x secondi",
		"es": "Actualizar estados cada x segundos",
		"pl": "Odśwież stany co x sekund",
		"zh-cn": "每x秒刷新一次状态"
	},
	"Notifications": {
		"en": "Notifications",
		"de": "Benachrichtigungen",
		"ru": "уведомление",
		"pt": "Notificações",
		"nl": "Meldingen",
		"fr": "Notifications",
		"it": "Notifiche",
		"es": "Notificaciones",
		"pl": "zgłoszenie"
	},
	"message type": {
		"en": "message type",
		"de": "Nachrichtentyp",
		"ru": "тип сообщения",
		"pt": "tipo de mensagem",
		"nl": "berichttype",
		"fr": "type de message",
		"it": "tipo di messaggio",
		"es": "Tipo de mensaje",
		"pl": "typ wiadomości",
		"zh-cn": "讯息类型"
	},
	"notifications type": {
		"en": "Notifications type",
		"de": "Benachrichtigungstyp",
		"ru": "тип уведомлений",
		"pt": "tipo de notificações",
		"nl": "type meldingen",
		"fr": "type de notifications",
		"it": "tipo di notifiche",
		"es": "tipo de notificaciones",
		"pl": "typ powiadomień"
	},
	"Notification Style": {
		"en": "Notification style",
		"de": "Benachrichtigungsstil",
		"ru": "Стиль уведомления",
		"pt": "Estilo de Notificação",
		"nl": "Meldingsstijl",
		"fr": "Style de notification",
		"it": "Stile di notifica",
		"es": "Estilo de notificación",
		"pl": "Styl powiadomienia"
	},
	"Waiting for the send (seconds)": {
		"en": "Wait before sending (seconds)",
		"de": "Warten vor dem Senden (Sekunden)",
		"ru": "Ожидание отправки (секунд)",
		"pt": "Aguardando o envio (segundos)",
		"nl": "Wachten op het verzenden (seconden)",
		"fr": "En attente de l'envoi (secondes)",
		"it": "In attesa dell'invio (secondi)",
		"es": "Esperando el envío (segundos)",
		"pl": "Oczekiwanie na wysłanie (sekundy)"
	},
	"Silent Notice": {
		"en": "Silent notice",
		"de": "Stille Benachrichtigung",
		"ru": "Безмолвное уведомление",
		"pt": "Aviso silencioso",
		"nl": "Stille opmerking",
		"fr": "Notice silencieuse",
		"it": "Avviso silenzioso",
		"es": "Aviso silencioso",
		"pl": "Cicha informacja"
	},
	"Long Notifications": {
		"en": "Long notifications",
		"de": "Lange Benachrichtigungen",
		"ru": "Длинные уведомления",
		"pt": "Notificações longas",
		"nl": "Lange meldingen",
		"fr": "Notifications longues",
		"it": "Notifiche lunghe",
		"es": "Notificaciones largas",
		"pl": "Długie powiadomienia"
	},
	"Short Notifications": {
		"en": "Short notifications",
		"de": "Kurze Benachrichtigungen",
		"ru": "Короткие уведомления",
		"pt": "Notificações breves",
		"nl": "Korte meldingen",
		"fr": "Notifications courtes",
		"it": "Brevi Notifiche",
		"es": "Notificaciones cortas",
		"pl": "Krótkie powiadomienia"
	},
	"Notification only on errors": {
		"en": "Notification only on errors",
		"de": "Benachrichtigung nur bei Fehlern",
		"ru": "Уведомление только об ошибках",
		"pt": "Notificação apenas em erros",
		"nl": "Alleen melding bij fouten",
		"fr": "Notification uniquement sur les erreurs",
		"it": "Notifica solo su errori",
		"es": "Notificación solo sobre errores",
		"pl": "Powiadomienie tylko o błędach"
	},
	"Notifications by telegram": {
		"en": "Notifications by telegram",
		"de": "Benachrichtigungen per Telegram",
		"ru": "Уведомления по Telegram",
		"pt": "Notificações por Telegram",
		"nl": "Meldingen per Telegram",
		"fr": "Notifications par Telegram",
		"it": "Notifiche via telegramma",
		"es": "Notificaciones por Telegram",
		"pl": "Powiadomienia za pomoca Telegram"
	},
	"Telegram": {
		"en": "Telegram",
		"de": "Telegram",
		"ru": "телеграм",
		"pt": "Telegram",
		"nl": "Telegram",
		"fr": "Télégram",
		"it": "Telegram",
		"es": "Telegram",
		"pl": "Telegram"
	},
	"Telegram Receiver": {
		"en": "Telegram recipient",
		"de": "Telegramempfänger",
		"ru": "Приемник телеграмм",
		"pt": "Receptor de telegrama",
		"nl": "Telegram-ontvanger",
		"fr": "Récepteur de télégramme",
		"it": "Telegram Receiver",
		"es": "Receptor de telegramas",
		"pl": "Odbiornik telegramu"
	},
	"Telegram instance": {
		"en": "Telegram instance",
		"de": "Telegram Instanz",
		"ru": "Экземпляр телеграмме",
		"pt": "Instância do telegrama",
		"nl": "Telegram-instantie",
		"fr": "Instance de télégramme",
		"it": "Istanza di Telegram",
		"es": "Instancia de Telegram",
		"pl": "Instancja telegramu"
	},
	"E-Mail": {
		"en": "E-mail",
		"de": "E-Mail",
		"ru": "Эл. почта",
		"pt": "O email",
		"nl": "E-mail",
		"fr": "Email",
		"it": "E-mail",
		"es": "Correo electrónico",
		"pl": "E-mail"
	},
	"email instance": {
		"en": "Email instance",
		"de": "E-Mail-Instanz",
		"ru": "экземпляр электронной почты",
		"pt": "instância de email",
		"nl": "email instantie",
		"fr": "instance de courrier électronique",
		"it": "istanza email",
		"es": "instancia de correo electrónico",
		"pl": "instancja e-mail"
	},
	"email receiver": {
		"en": "Email recipient",
		"de": "E-Mail-Empfänger",
		"ru": "приемник электронной почты",
		"pt": "receptor de e-mail",
		"nl": "e-mail ontvanger",
		"fr": "destinataire du courrier électronique",
		"it": "ricevitore e-mail",
		"es": "receptor de correo electrónico",
		"pl": "odbiornik e-mail"
	},
	"email sender": {
		"en": "Email sender",
		"de": "E-Mail-Absender",
		"ru": "отправитель электронной почты",
		"pt": "remetente de email",
		"nl": "e-mail afzender",
		"fr": "email expéditeur",
		"it": "mittente dell'e-mail",
		"es": "remitente de correo electrónico",
		"pl": "e-mail nadawcy"
	},
	"WhatsApp": {
		"en": "WhatsApp",
		"de": "WhatsApp",
		"ru": "WhatsApp",
		"pt": "WhatsApp",
		"nl": "WhatsApp",
		"fr": "WhatsApp",
		"it": "WhatsApp",
		"es": "WhatsApp",
		"pl": "WhatsApp"
	},
	"WhatsApp instance": {
		"en": "WhatsApp instance",
		"de": "WhatsApp-Instanz",
		"ru": "Экземпляр WhatsApp",
		"pt": "Instância WhatsApp",
		"nl": "WhatsApp-exemplaar",
		"fr": "Instance WhatsApp",
		"it": "Istanza WhatsApp",
		"es": "Instancia de whatsapp",
		"pl": "Instancja WhatsApp"
	},
	"Pushover": {
		"en": "Pushover",
		"de": "Pushover",
		"ru": "Pushover",
		"pt": "Pushover",
		"nl": "Pushover",
		"fr": "Pushover",
		"it": "Pushover",
		"es": "Pushover",
		"pl": "Pushover"
	},
	"Pushover instance": {
		"en": "Pushover instance",
		"de": "Pushover-Instanz",
		"ru": "Экземпляр Pushover",
		"pt": "Instância de pushover",
		"nl": "Pushover-instantie",
		"fr": "Instance de pushover",
		"it": "Istanza pushover",
		"es": "Instancia pushover",
		"pl": "Instalacja pushover"
	},
	"device ID (optional)": {
		"en": "Device ID (optional)",
		"de": "Geräte-ID (optional)",
		"ru": "идентификатор устройства (необязательно)",
		"pt": "ID do dispositivo (opcional)",
		"nl": "apparaat-ID (optioneel)",
		"fr": "ID de périphérique (facultatif)",
		"it": "ID dispositivo (opzionale)",
		"es": "ID del dispositivo (opcional)",
		"pl": "identyfikator urządzenia (opcjonalnie)"
	},
	"Enable / Disable Notifications": {
		"en": "Enable / disable notifications",
		"de": "Benachrichtigungen aktivieren / deaktivieren",
		"ru": "Включение и отключение уведомлений",
		"pt": "Ativar / desativar notificações",
		"nl": "Meldingen in- / uitschakelen",
		"fr": "Activer / désactiver les notifications",
		"it": "Abilita / disabilita le notifiche",
		"es": "Habilitar / deshabilitar notificaciones",
		"pl": "Włącz / wyłącz powiadomienia"
	},
	"Informations": {
		"en": "Informations",
		"de": "Informationen",
		"ru": "Информация",
		"pt": "Informações",
		"nl": "Informatie",
		"fr": "Informations",
		"it": "Informazioni",
		"es": "Informaciones",
		"pl": "Informacje",
		"zh-cn": "资讯资讯"
	},
	"informations": {
		"en": "informations",
		"de": "Informationen",
		"ru": "информация",
		"pt": "informações",
		"nl": "informatie",
		"fr": "informations",
		"it": "informazioni",
		"es": "informaciones",
		"pl": "informacje",
		"zh-cn": "资讯"
	},
	"warnings": {
		"en": "warnings",
		"de": "Warnungen",
		"ru": "предупреждения",
		"pt": "avisos",
		"nl": "waarschuwingen",
		"fr": "mises en garde",
		"it": "avvertenze",
		"es": "advertencias",
		"pl": "ostrzeżenia",
		"zh-cn": "警告"
	},
	"errors": {
		"en": "errors",
		"de": "Fehler",
		"ru": "ошибки",
		"pt": "erros",
		"nl": "fouten",
		"fr": "les erreurs",
		"it": "errori",
		"es": "errores",
		"pl": "błędy",
		"zh-cn": "错误"
	},
	"select the types for notifications": {
		"en": "select the types for notifications",
		"de": "Wählen Sie die Typen für Benachrichtigungen aus",
		"ru": "выберите типы уведомлений",
		"pt": "selecione os tipos de notificações",
		"nl": "selecteer de typen voor meldingen",
		"fr": "sélectionnez les types de notifications",
		"it": "seleziona i tipi di notifiche",
		"es": "seleccione los tipos de notificaciones",
		"pl": "wybierz typy powiadomień",
		"zh-cn": "选择通知的类型"
	},
	"no notifications": {
		"en": "no notifications",
		"de": "keine Benachrichtigungen",
		"ru": "нет уведомлений",
		"pt": "nenhuma notificação",
		"nl": "geen notificaties",
		"fr": "aucune notification",
		"it": "nessuna notifica",
		"es": "no Notificaciones",
		"pl": "brak powiadomień",
		"zh-cn": "没有通知"
	},
	"informations, warnings": {
		"en": "informations, warnings",
		"de": "Informationen, Warnungen",
		"ru": "информация, предупреждения",
		"pt": "informações, avisos",
		"nl": "informatie, waarschuwingen",
		"fr": "informations, avertissements",
		"it": "informazioni, avvertenze",
		"es": "informaciones, advertencias",
		"pl": "informacje, ostrzeżenia",
		"zh-cn": "信息，警告"
	},
	"informations, errors": {
		"en": "informations, errors",
		"de": "Informationen, Fehler",
		"ru": "информация, ошибки",
		"pt": "informações, erros",
		"nl": "informatie, fouten",
		"fr": "informations, erreurs",
		"it": "informazioni, errori",
		"es": "informaciones, errores",
		"pl": "informacje, błędy",
		"zh-cn": "信息，错误"
	},
	"warnings, errors": {
		"en": "warnings, errors",
		"de": "Warnungen, Fehler",
		"ru": "предупреждения, ошибки",
		"pt": "avisos, erros",
		"nl": "waarschuwingen, fouten",
		"fr": "avertissements, erreurs",
		"it": "avvertenze, errori",
		"es": "advertencias, errores",
		"pl": "ostrzeżenia, błędy",
		"zh-cn": "警告，错误"
	},
	"informations, warnings, errors": {
		"en": "informations, warnings, errors",
		"de": "Informationen, Warnungen, Fehler",
		"ru": "информация, предупреждения, ошибки",
		"pt": "informações, avisos, erros",
		"nl": "informatie, waarschuwingen, fouten",
		"fr": "informations, avertissements, erreurs",
		"it": "informazioni, avvisi, errori",
		"es": "información, advertencias, errores",
		"pl": "informacje, ostrzeżenia, błędy",
		"zh-cn": "信息，警告，错误"
	},
	"API Request homestatus was sent to API each": {
		"en": "API Request homestatus was sent to API each",
		"de": "Der API-Anforderungshomestatus wurde jeweils an die API gesendet",
		"ru": "Статус домашнего статуса запроса API был отправлен в API каждый",
		"pt": "O status do pedido de API foi enviado para cada API",
		"nl": "API Request homestatus is elk naar de API gestuurd",
		"fr": "Le statut de la demande d'API a été envoyé à l'API chacun",
		"it": "Lo stato iniziale della richiesta API è stato inviato a ciascuna API",
		"es": "Homestatus de solicitud de API se envió a API cada",
		"pl": "Status domowy żądania API został wysłany do API",
		"zh-cn": "每个API请求homestatus已发送到API"
	},
	"seconds": {
		"en": "seconds",
		"de": "Sekunden",
		"ru": "секунды",
		"pt": "segundos",
		"nl": "seconden",
		"fr": "secondes",
		"it": "secondi",
		"es": "segundos",
		"pl": "sekundy",
		"zh-cn": "秒"
	},
	"Refresh homestatus interval": {
		"en": "Refresh homestatus interval",
		"de": "Homestatus-Intervall aktualisieren",
		"ru": "Интервал обновления домашнего статуса",
		"pt": "Atualizar intervalo de status de origem",
		"nl": "Vernieuw homestatus-interval",
		"fr": "Actualiser l'intervalle de statut homologue",
		"it": "Aggiorna l'intervallo di stato iniziale",
		"es": "Actualizar intervalo de homestatus",
		"pl": "Odśwież interwał homestatus",
		"zh-cn": "刷新本机状态间隔"
	},
	"Target temperature changed": {
		"en": "Target temperature changed",
		"de": "Zieltemperatur geändert",
		"ru": "Целевая температура изменена",
		"pt": "Temperatura alvo alterada",
		"nl": "Gewenste temperatuur gewijzigd",
		"fr": "La température cible a changé",
		"it": "La temperatura target è cambiata",
		"es": "La temperatura objetivo cambió",
		"pl": "Temperatura docelowa zmieniona",
		"zh-cn": "目标温度已更改"
	},
	"Mode for your heating system was set to": {
		"en": "Mode for your heating system was set to",
		"de": "Der Modus für Ihr Heizsystem wurde eingestellt auf",
		"ru": "Для вашей системы отопления установлен режим",
		"pt": "O modo do seu sistema de aquecimento foi definido como",
		"nl": "De modus voor uw verwarmingssysteem was ingesteld op",
		"fr": "Le mode de votre système de chauffage a été réglé sur",
		"it": "La modalità del sistema di riscaldamento era impostata su",
		"es": "El modo de su sistema de calefacción se estableció en",
		"pl": "Tryb ogrzewania został ustawiony na",
		"zh-cn": "您的供暖系统的模式设置为"
	},
	"Changed schedule for your heating system to": {
		"en": "Changed schedule for your heating system to",
		"de": "Geänderter Zeitplan für Ihr Heizsystem auf",
		"ru": "Изменено расписание вашей системы отопления на",
		"pt": "Cronograma alterado para seu sistema de aquecimento para",
		"nl": "Tijdschema voor uw verwarmingssysteem gewijzigd in",
		"fr": "Horaire modifié de votre système de chauffage pour",
		"it": "Programma modificato per il tuo sistema di riscaldamento in",
		"es": "Se cambió el horario de su sistema de calefacción a",
		"pl": "Zmieniono harmonogram systemu grzewczego na",
		"zh-cn": "将加热系统的时间表更改为"
	},
	"Changed weekly schedule": {
		"en": "Changed weekly schedule",
		"de": "Wochenplan geändert auf",
		"ru": "Изменено недельное расписание",
		"pt": "Cronograma semanal alterado",
		"nl": "Gewijzigd wekelijks schema",
		"fr": "Horaire hebdomadaire modifié",
		"it": "Programma settimanale modificato",
		"es": "Horario semanal modificado",
		"pl": "Zmieniony harmonogram tygodniowy",
		"zh-cn": "更改每周时间表"
	},
	"for your heating system": {
		"en": "for your heating system",
		"de": "für Ihr Heizsystem",
		"ru": "для вашей системы отопления",
		"pt": "para o seu sistema de aquecimento",
		"nl": "voor uw verwarmingssysteem",
		"fr": "pour votre système de chauffage",
		"it": "per il tuo impianto di riscaldamento",
		"es": "para su sistema de calefacción",
		"pl": "dla Twojego systemu grzewczego",
		"zh-cn": "用于您的加热系统"
	},
	"API-synchomeschedule request is missing parameters": {
		"en": "API-synchomeschedule request is missing parameters",
		"de": "API-synchomeschedule-Anfrage fehlen Parameter",
		"ru": "В запросе API-synchomeschedule отсутствуют параметры",
		"pt": "A solicitação API-synchomeschedule não tem parâmetros",
		"nl": "API-synchronisatieschema-verzoek mist parameters",
		"fr": "La requête API-synchomeschedule manque de paramètres",
		"it": "Nella richiesta API-synchomeschedule mancano i parametri",
		"es": "A la solicitud API-synchomeschedule le faltan parámetros",
		"pl": "W żądaniu API-synchomeschedule brakuje parametrów",
		"zh-cn": "API-synchomeschedule 请求缺少参数"
	},
	"Start refresh request": {
		"en": "Start refresh request",
		"de": "Aktualisierungsanforderung starten",
		"ru": "Начать запрос на обновление",
		"pt": "Iniciar solicitação de atualização",
		"nl": "Vernieuwingsverzoek starten",
		"fr": "Démarrer la demande d'actualisation",
		"it": "Avvia richiesta di aggiornamento",
		"es": "Iniciar solicitud de actualización",
		"pl": "Rozpocznij żądanie odświeżenia",
		"zh-cn": "开始刷新请求"
	},
	"Set room attributes": {
		"en": "Set room übertragen",
		"de": "Raumattribute festlegen",
		"ru": "Установить атрибуты комнаты",
		"pt": "Definir atributos da sala",
		"nl": "Kamerkenmerken instellen",
		"fr": "Définir les attributs de la pièce",
		"it": "Imposta gli attributi della stanza",
		"es": "Establecer atributos de la habitación",
		"pl": "Ustaw atrybuty pokoju",
		"zh-cn": "设置房间属性"
	},
	"Retrieved statistic for a specific room": {
		"en": "Retrieved statistic for a specific room",
		"de": "Abgerufene Statistik für einen bestimmten Raum",
		"ru": "Полученная статистика для конкретной комнаты",
		"pt": "Estatística recuperada para uma sala específica",
		"nl": "Statistiek voor een specifieke kamer opgehaald",
		"fr": "Statistiques récupérées pour une salle spécifique",
		"it": "Statistica recuperata per una stanza specifica",
		"es": "Estadística recuperada para una habitación específica",
		"pl": "Pobrane statystyki dla określonego pomieszczenia",
		"zh-cn": "检索特定房间的统计信息"
	},
	"Retrieved statistic for a specific room number": {
		"en": "Retrieved statistic for a specific room number",
		"de": "Abgerufene Statistik für eine bestimmte Zimmernummer",
		"ru": "Полученная статистика для определенного номера комнаты",
		"pt": "Estatística recuperada para um número de quarto específico",
		"nl": "Statistiek opgehaald voor een specifiek kamernummer",
		"fr": "Statistiques récupérées pour un numéro de chambre spécifique",
		"it": "Statistica recuperata per un numero di stanza specifico",
		"es": "Estadística recuperada para un número de habitación específico",
		"pl": "Pobrano statystyki dla określonego numeru pokoju",
		"zh-cn": "检索特定房间号的统计信息"
	},
	"Boiler historical data was retrieved from device": {
		"en": "Boiler historical data was retrieved from device",
		"de": "Die historischen Daten des Kessels wurden von folgendem Gerät abgerufen",
		"ru": "Исторические данные котла были получены с устройства",
		"pt": "Os dados históricos da caldeira foram recuperados do dispositivo",
		"nl": "Historische gegevens van de ketel zijn opgehaald van het apparaat",
		"fr": "Les données historiques de la chaudière ont été extraites de l'appareil",
		"it": "I dati storici della caldaia sono stati recuperati dal dispositivo",
		"es": "Los datos históricos de la caldera se recuperaron del dispositivo",
		"pl": "Pobrano historyczne dane kotła z urządzenia",
		"zh-cn": "从设备检索锅炉历史数据"
	},
	"Boiler historical data was retrieved from device address": {
		"en": "Boiler historical data was retrieved from device address",
		"de": "Die historischen Daten des Kessels wurden von der folgenden Geräteadresse abgerufen",
		"ru": "Исторические данные котла получены с адреса устройства.",
		"pt": "Os dados históricos da caldeira foram recuperados do endereço do dispositivo",
		"nl": "De historische gegevens van de ketel zijn opgehaald uit het apparaatadres",
		"fr": "Les données historiques de la chaudière ont été extraites de l'adresse de l'appareil",
		"it": "I dati storici della caldaia sono stati recuperati dall'indirizzo del dispositivo",
		"es": "Los datos históricos de la caldera se recuperaron de la dirección del dispositivo",
		"pl": "Pobrano dane historyczne kotła z adresu urządzenia",
		"zh-cn": "从设备地址检索锅炉历史数据"
	},
	"Start Token-request:": {
		"en": "Start Token-request:",
		"de": "Token-Anfrage starten:",
		"ru": "Начать токен-запрос:",
		"pt": "Iniciar solicitação de token:",
		"nl": "Start token-aanvraag:",
		"fr": "Démarrez la demande de jeton:",
		"it": "Avvia richiesta di token:",
		"es": "Iniciar solicitud de token:",
		"pl": "Rozpocznij żądanie tokena:",
		"zh-cn": "启动令牌请求："
	},
	"Token OK:": {
		"en": "Token OK:",
		"de": "Token OK:",
		"ru": "Токен в порядке:",
		"pt": "Token OK:",
		"nl": "Token OK:",
		"fr": "Jeton OK:",
		"it": "Token OK:",
		"es": "Token OK:",
		"pl": "Token OK:",
		"zh-cn": "令牌确定："
	},
	"Did not get a tokencode:": {
		"en": "Did not get a tokencode:",
		"de": "Ich habe keinen Tokencode erhalten:",
		"ru": "Не получил токен-код:",
		"pt": "Não obteve um tokencode:",
		"nl": "Geen tokencode ontvangen:",
		"fr": "N'a pas obtenu de code de jeton:",
		"it": "Non ho ricevuto un codice token:",
		"es": "No obtuve un código de token:",
		"pl": "Nie otrzymałem kodu tokena:",
		"zh-cn": "没有获得令牌代码："
	},
	"API Token": {
		"en": "API Token",
		"de": "API-Token",
		"ru": "Токен API",
		"pt": "Token API",
		"nl": "API-token",
		"fr": "Jeton API",
		"it": "Token API",
		"es": "Token de API",
		"pl": "Token API",
		"zh-cn": "API令牌"
	},
	"Start API-request:": {
		"en": "Start API-request:",
		"de": "API-Anfrage starten:",
		"ru": "Запустить API-запрос:",
		"pt": "Iniciar solicitação de API:",
		"nl": "Start API-aanvraag:",
		"fr": "Démarrez la requête API:",
		"it": "Avvia richiesta API:",
		"es": "Iniciar solicitud de API:",
		"pl": "Uruchom żądanie API:",
		"zh-cn": "启动API请求："
	},
	"API request not OK:": {
		"en": "API request not OK:",
		"de": "API-Anfrage nicht OK:",
		"ru": "Запрос API не в порядке:",
		"pt": "A solicitação de API não está OK:",
		"nl": "API-verzoek niet OK:",
		"fr": "La demande d'API n'est pas OK:",
		"it": "Richiesta API non OK:",
		"es": "La solicitud de API no está bien:",
		"pl": "Żądanie API nie jest OK:",
		"zh-cn": "API请求不正确："
	},
	"Changed the thermmode manually": {
		"en": "Changed the thermmode manually",
		"de": "Thermometer manuell geändert",
		"ru": "Поменял терморежим вручную",
		"pt": "Alterou o termodo manualmente",
		"nl": "De thermmode handmatig gewijzigd",
		"fr": "Changé le thermmode manuellement",
		"it": "Modificato manualmente il thermmode",
		"es": "Cambió el termodo manualmente",
		"pl": "Zmieniono termometr ręcznie",
		"zh-cn": "手动更改热模式"
	},
	"API changes applied": {
		"en": "API changes applied",
		"de": "API-Änderungen angewendet",
		"ru": "Изменения API применены",
		"pt": "Alterações de API aplicadas",
		"nl": "API-wijzigingen toegepast",
		"fr": "Modifications de l'API appliquées",
		"it": "Modifiche API applicate",
		"es": "Se aplicaron los cambios de API",
		"pl": "Zastosowano zmiany interfejsu API",
		"zh-cn": "已应用API更改"
	},
	"API request finished": {
		"en": "API request finished",
		"de": "API-Anfrage beendet",
		"ru": "Запрос API завершен",
		"pt": "Pedido de API concluído",
		"nl": "API-verzoek voltooid",
		"fr": "Demande d'API terminée",
		"it": "Richiesta API terminata",
		"es": "Solicitud de API finalizada",
		"pl": "Żądanie API zakończone",
		"zh-cn": "API请求已完成"
	},
	"Request:": {
		"en": "Request:",
		"de": "Anfrage:",
		"ru": "Запрос:",
		"pt": "Solicitação:",
		"nl": "Verzoek:",
		"fr": "Demande:",
		"it": "Richiesta:",
		"es": "Solicitud:",
		"pl": "Żądanie:",
		"zh-cn": "请求："
	},
	"API-getroosmeasure request is missing parameters": {
		"en": "API-getroosmeasure request is missing parameters",
		"de": "Bei der API-Getroosmeasure-Anforderung fehlen Parameter",
		"ru": "В запросе API-getroosmeasure отсутствуют параметры",
		"pt": "A solicitação API-getroosmeasure está sem parâmetros",
		"nl": "API-getroosmeasure-verzoek mist parameters",
		"fr": "La requête API-getroosmeasure n'a pas de paramètres",
		"it": "Nella richiesta API-getroosmeasure mancano i parametri",
		"es": "A la solicitud API-getroosmeasure le faltan parámetros",
		"pl": "W żądaniu API-getroosmeasure brakuje parametrów",
		"zh-cn": "API-getroosmeasure请求缺少参数"
	},
	"Request is missing parameters": {
		"en": "Request is missing parameters",
		"de": "Anfrage fehlen Parameter",
		"ru": "В запросе отсутствуют параметры",
		"pt": "A solicitação está sem parâmetros",
		"nl": "Verzoek mist parameters",
		"fr": "La requête n'a pas de paramètres",
		"it": "Nella richiesta mancano i parametri",
		"es": "A la solicitud le faltan parámetros",
		"pl": "W żądaniu brakuje parametrów",
		"zh-cn": "请求缺少参数"
	},
	"Actual payload:": {
		"en": "Actual payload:",
		"de": "Tatsächliche Nutzlast:",
		"ru": "Фактическая полезная нагрузка:",
		"pt": "Carga útil real:",
		"nl": "Werkelijke laadvermogen:",
		"fr": "Charge utile réelle:",
		"it": "Carico utile effettivo:",
		"es": "Carga útil real:",
		"pl": "Rzeczywista ładowność:",
		"zh-cn": "实际有效载荷："
	},
	"API-getmeasure request is missing parameters": {
		"en": "API-getmeasure request is missing parameters",
		"de": "Bei der API-Getmeasure-Anforderung fehlen Parameter",
		"ru": "В запросе API-getmeasure отсутствуют параметры",
		"pt": "A solicitação API-getmeasure está sem parâmetros",
		"nl": "API-getmeasure-verzoek mist parameters",
		"fr": "La requête API-getmeasure n'a pas de paramètres",
		"it": "Nella richiesta API-getmeasure mancano i parametri",
		"es": "A la solicitud API-getmeasure le faltan parámetros",
		"pl": "W żądaniu API-getmeasure brakuje parametrów",
		"zh-cn": "API-getmeasure请求缺少参数"
	},
	"Invalid Parameter": {
		"en": "Invalid Parameter",
		"de": "Ungültiger Parameter",
		"ru": "Неверный параметр",
		"pt": "Parâmetro inválido",
		"nl": "Ongeldige parameter",
		"fr": "Paramètre invalide",
		"it": "Parametro non valido",
		"es": "Parametro invalido",
		"pl": "Niewłaściwy parametr",
		"zh-cn": "无效的参数"
	},
	"Did not get url or payload!": {
		"en": "Did not get url or payload!",
		"de": "Keine URL oder payload bekommen!",
		"ru": "Не получен URL или полезная нагрузка!",
		"pt": "Não obteve url ou carga útil!",
		"nl": "Geen url of payload ontvangen!",
		"fr": "N'a pas obtenu l'URL ou la charge utile!",
		"it": "Non ho ricevuto l'URL o il payload!",
		"es": "¡No obtuve la URL ni la carga útil!",
		"pl": "Nie otrzymano adresu URL ani ładunku!",
		"zh-cn": "没有获得URL或有效载荷！"
	},
	"Netatmo API status:": {
		"en": "Netatmo API status:",
		"de": "Netatmo API-Status:",
		"ru": "Статус Netatmo API:",
		"pt": "Status da API Netatmo:",
		"nl": "Netatmo API-status:",
		"fr": "État de l'API Netatmo:",
		"it": "Stato API Netatmo:",
		"es": "Estado de la API de Netatmo:",
		"pl": "Stan API Netatmo:",
		"zh-cn": "Netatmo API状态："
	},
	"cleaned everything up...": {
		"en": "cleaned everything up...",
		"de": "alles aufgeräumt ...",
		"ru": "почистил все ...",
		"pt": "limpou tudo ...",
		"nl": "alles opgeruimd ...",
		"fr": "tout nettoyé ...",
		"it": "ripulito tutto ...",
		"es": "limpió todo ...",
		"pl": "posprzątałem wszystko ...",
		"zh-cn": "清理一切..."
	},
	"Adapter": {
		"en": "Adapter",
		"de": "Adapter",
		"ru": "Адаптер",
		"pt": "Adaptador",
		"nl": "Adapter",
		"fr": "Adaptateur",
		"it": "Adattatore",
		"es": "Adaptador",
		"pl": "Adapter",
		"zh-cn": "适配器"
	},
	"Adapter stopped": {
		"en": "Adapter stopped",
		"de": "Adapter gestoppt",
		"ru": "Адаптер остановлен",
		"pt": "Adaptador parado",
		"nl": "Adapter gestopt",
		"fr": "Adaptateur arrêté",
		"it": "Adattatore arrestato",
		"es": "Adaptador detenido",
		"pl": "Adapter zatrzymał się",
		"zh-cn": "适配器已停止"
	},
	"Somebody stopped": {
		"en": "Somebody stopped",
		"de": "Jemand blieb stehen",
		"ru": "Кто-то остановился",
		"pt": "Alguem parou",
		"nl": "Iemand stopte",
		"fr": "Quelqu'un s'est arrêté",
		"it": "Qualcuno si è fermato",
		"es": "Alguien se detuvo",
		"pl": "Ktoś się zatrzymał",
		"zh-cn": "有人停了下来"
	},
	"API Request homesdata:": {
		"en": "API Request homesdata:",
		"de": "API-Anfrage homesdata:",
		"ru": "API-запрос homesdata:",
		"pt": "Dados domésticos de solicitação de API:",
		"nl": "API-aanvraag homesdata:",
		"fr": "Demande d'API homesdata:",
		"it": "Dati della richiesta API:",
		"es": "API Solicitar datos de inicio:",
		"pl": "Homesdata żądania API:",
		"zh-cn": "API请求房屋数据："
	},
	"API Request homestatus:": {
		"en": "API Request homestatus:",
		"de": "API Request homestatus:",
		"ru": "Домашний статус запроса API:",
		"pt": "Homestatus de solicitação de API:",
		"nl": "API Request homestatus:",
		"fr": "Statut de la demande d'API:",
		"it": "Homestatus richiesta API:",
		"es": "Homestatus de solicitud de API:",
		"pl": "Status domowy żądania API:",
		"zh-cn": "API请求状态："
	},
	"API Request getroommeasure:": {
		"en": "API Request getroommeasure:",
		"de": "API Request getroommeasure:",
		"ru": "Запрос API getroommeasure:",
		"pt": "Solicitação de API getroommeasure:",
		"nl": "API Request getroommeasure:",
		"fr": "Demande d'API getroommeasure:",
		"it": "Richiesta API getroommeasure:",
		"es": "API Solicitar getroommeasure:",
		"pl": "API request getroommeasure:",
		"zh-cn": "API请求getroommeasure："
	},
	"API Request getmeasure:": {
		"en": "API Request getmeasure:",
		"de": "API-Anforderung getmeasure:",
		"ru": "Запрос API getmeasure:",
		"pt": "Getmeasure de solicitação de API:",
		"nl": "API Request-maatregel:",
		"fr": "Demande d'API getmeasure:",
		"it": "Richiesta API getmeasure:",
		"es": "Solicitud de API getmeasure:",
		"pl": "Getmeasure żądanie API:",
		"zh-cn": "API请求getmeasure："
	},
	"Call API directly": {
		"en": "Call API directly",
		"de": "API direkt aufrufen",
		"ru": "Вызов API напрямую",
		"pt": "Chame a API diretamente",
		"nl": "Roep API rechtstreeks aan",
		"fr": "Appeler directement l'API",
		"it": "Chiama direttamente l'API",
		"es": "Llamar a API directamente",
		"pl": "Wywołaj API bezpośrednio",
		"zh-cn": "直接调用API"
	},
	"No Number": {
		"en": "No Number",
		"de": "Keine Nummer",
		"ru": "Нет номера",
		"pt": "Nenhum número",
		"nl": "Geen nummer",
		"fr": "Pas de numéro",
		"it": "Nessun numero",
		"es": "Sin número",
		"pl": "Brak numeru",
		"zh-cn": "没有号码"
	},
	"Set TempChanged manually": {
		"en": "Set TempChanged manually",
		"de": "TempChanged manuell eingestellt",
		"ru": "Установить TempChanged вручную",
		"pt": "Definir TempChanged manualmente",
		"nl": "Stel TempChanged handmatig in",
		"fr": "Définir manuellement TempChanged",
		"it": "Imposta TempChanged manualmente",
		"es": "Establecer TempChanged manualmente",
		"pl": "Ustaw TempChanged ręcznie",
		"zh-cn": "手动设置TempChanged"
	},
	"Cannot parse stored user IDs from Telegram!": {
		"en": "Cannot parse stored user IDs from Telegram!",
		"de": "Gespeicherte Benutzer-IDs von Telegram können nicht geparst werden!",
		"ru": "Не удается разобрать сохраненные идентификаторы пользователей из Telegram!",
		"pt": "Não é possível analisar os IDs de usuário armazenados no Telegram!",
		"nl": "Kan opgeslagen gebruikers-ID's van Telegram niet ontleden!",
		"fr": "Impossible d'analyser les ID utilisateur stockés à partir de Telegram !",
		"it": "Impossibile analizzare gli ID utente memorizzati da Telegram!",
		"es": "¡No se pueden analizar los ID de usuario almacenados de Telegram!",
		"pl": "Nie można przeanalizować zapisanych identyfikatorów użytkowników z Telegrama!",
		"zh-cn": "无法从 Telegram 解析存储的用户 ID！"
	},
	"SetTemp: ": {
		"en": "SetTemp: ",
		"de": "SetTemp:",
		"ru": "Заданная температура:",
		"pt": "SetTemp:",
		"nl": "Temp instellen:",
		"fr": "Définir la température :",
		"it": "Imposta Temp:",
		"es": "Establecer temperatura:",
		"pl": "Nastaw temperaturę:",
		"zh-cn": "设置温度："
	},
	"API Request setthermpoint": {
		"en": "API Request setthermpoint",
		"de": "API Request setthermpoint",
		"ru": "Установка запроса API",
		"pt": "Setthermpoint de solicitação de API",
		"nl": "API-aanvraag setthermpoint",
		"fr": "Demande d'API setthermpoint",
		"it": "API Richiedi setthermpoint",
		"es": "Solicitud de API setthermpoint",
		"pl": "API żądanie setthermpoint",
		"zh-cn": "API请求setthermpoint"
	},
	"API Request synchomeschedule:": {
		"en": "API Request synchomeschedule:",
		"de": "Synchronisationsplan für API-Anforderungen:",
		"ru": "График синхронизации запросов API:",
		"pt": "Programação de sincronização de solicitação de API:",
		"nl": "Synchronisatieschema voor API-aanvragen:",
		"fr": "Calendrier de synchronisation de la demande d'API:",
		"it": "Programma di sincronizzazione delle richieste API:",
		"es": "Calendario de sincronización de solicitudes de API:",
		"pl": "Harmonogram synchronizacji żądań API:",
		"zh-cn": "API请求同步时间表："
	},
	"API Request swithhomeschedule:": {
		"en": "API Request swithhomeschedule:",
		"de": "API-Anfrage swithhomeschedule:",
		"ru": "Расписание запросов API:",
		"pt": "Programação de programação de solicitação de API:",
		"nl": "API Request swithhomeschedule:",
		"fr": "Demande d'API swithhomeschedule:",
		"it": "Richiesta API swithhomeschedule:",
		"es": "Solicitud de API swithhomeschedule:",
		"pl": "Harmonogram żądania interfejsu API:",
		"zh-cn": "API请求swithhomeschedule："
	},
	"Status": {
		"en": "Status",
		"de": "Status",
		"ru": "Положение дел",
		"pt": "Status",
		"nl": "Toestand",
		"fr": "Statut",
		"it": "Stato",
		"es": "Estado",
		"pl": "Status",
		"zh-cn": "状态"
	},
	"changed manually": {
		"en": "changed manually",
		"de": "manuell geändert",
		"ru": "изменено вручную",
		"pt": "alterado manualmente",
		"nl": "handmatig gewijzigd",
		"fr": "changé manuellement",
		"it": "cambiato manualmente",
		"es": "cambiado manualmente",
		"pl": "zmieniane ręcznie",
		"zh-cn": "手动更改"
	},
	"away from home": {
		"en": "'away from home'",
		"de": "'nicht zu Hause'",
		"ru": "'вдали от дома'",
		"pt": "'longe de casa'",
		"nl": "'weg van huis'",
		"fr": "'Loin de la maison'",
		"it": "'lontano da casa'",
		"es": "'lejos de casa'",
		"pl": "'daleko od domu'",
		"zh-cn": "离开家"
	},
	"schedule": {
		"en": "'schedule'",
		"de": "'Zeitplan'",
		"ru": "'график'",
		"pt": "'cronograma'",
		"nl": "'schema'",
		"fr": "'programme'",
		"it": "'programma'",
		"es": "'calendario'",
		"pl": "'harmonogram'",
		"zh-cn": "'时间表'"
	},
	"frost guard": {
		"en": "'frost guard'",
		"de": "'Frostschutz'",
		"ru": "'морозник'",
		"pt": "'guarda geada'",
		"nl": "'vorstbewaker'",
		"fr": "'garde-gel'",
		"it": "\"protezione antigelo\"",
		"es": "'guardia de escarcha'",
		"pl": "„ochrona przed mrozem”",
		"zh-cn": "“防冻罩”"
	},
	"Refresh whole structure:": {
		"en": "Refresh whole structure:",
		"de": "Gesamte Struktur aktualisieren:",
		"ru": "Обновить всю структуру:",
		"pt": "Atualize toda a estrutura:",
		"nl": "Vernieuw de hele structuur:",
		"fr": "Rafraîchir toute la structure:",
		"it": "Aggiorna l'intera struttura:",
		"es": "Actualizar toda la estructura:",
		"pl": "Odśwież całą strukturę:",
		"zh-cn": "刷新整个结构："
	},
	"Netatmo API request aborted": {
		"en": "Netatmo API request aborted",
		"de": "Netatmo API-Anforderung abgebrochen",
		"ru": "Запрос Netatmo API прерван",
		"pt": "Solicitação da API Netatmo abortada",
		"nl": "Netatmo API-verzoek afgebroken",
		"fr": "Demande d'API Netatmo abandonnée",
		"it": "Richiesta API Netatmo interrotta",
		"es": "Solicitud de API de Netatmo cancelada",
		"pl": "Żądanie Netatmo API zostało przerwane",
		"zh-cn": "Netatmo API请求中止"
	},
	"API Request homestatus sent to API each": {
		"en": "API Request homestatus sent to API each",
		"de": "API Request homestatus jeweils an API gesendet",
		"ru": "Домашний статус запроса API отправляется в API каждый",
		"pt": "Status inicial da solicitação de API enviado para a API a cada",
		"nl": "API-verzoek homestatus elk naar API verzonden",
		"fr": "Demande d'API homestatus envoyé à l'API chaque",
		"it": "API Request homestatus inviato all'API ciascuno",
		"es": "Solicitud de API HomeStatus enviada a API cada",
		"pl": "API Request homestatus wysyłane do API każdego z nich",
		"zh-cn": "API请求homestatus发送到API每个"
	},
	"Netatmo API status false": {
		"en": "Netatmo API status false",
		"de": "Netatmo-API-Status falsch",
		"ru": "Неверный статус API Netatmo",
		"pt": "Status da API Netatmo falso",
		"nl": "Netatmo API-status false",
		"fr": "Statut de l'API Netatmo faux",
		"it": "Stato API Netatmo falso",
		"es": "Estado de la API de Netatmo falso",
		"pl": "Fałszywy stan interfejsu API Netatmo",
		"zh-cn": "Netatmo API 状态为假"
	},
	"API Request setthermmode": {
		"en": "API Request setthermmode",
		"de": "API-Anfrage setthermmode",
		"ru": "Запрос API",
		"pt": "Solicitação de API setthermmode",
		"nl": "API-verzoek setthermmode",
		"fr": "Requête API setthermmode",
		"it": "Richiesta API in modalità setthermode",
		"es": "Solicitud de API setthermmode",
		"pl": "Ustaw tryb termiczny żądania API",
		"zh-cn": "API 请求 setthermmode"
	},
	"Can not save data to objects: ": {
		"en": "Can not save data to objects: ",
		"de": "Daten können nicht in Objekten gespeichert werden: ",
		"ru": "Не удается сохранить данные в объекты: ",
		"pt": "Não é possível salvar dados em objetos: ",
		"nl": "Kan geen gegevens naar objecten opslaan: ",
		"fr": "Impossible d'enregistrer les données dans les objets : ",
		"it": "Impossibile salvare i dati negli oggetti: ",
		"es": "No se pueden guardar datos en objetos: ",
		"pl": "Nie można zapisać danych do obiektów: ",
		"zh-cn": "无法将数据保存到对象："
	},
	"Can not create device: ": {
		"en": "Can not create device: ",
		"de": "Gerät kann nicht erstellt werden: ",
		"ru": "Невозможно создать устройство: ",
		"pt": "Não é possível criar o dispositivo: ",
		"nl": "Kan apparaat niet maken: ",
		"fr": "Impossible de créer l'appareil : ",
		"it": "Impossibile creare il dispositivo: ",
		"es": "No se puede crear el dispositivo: ",
		"pl": "Nie można utworzyć urządzenia: ",
		"zh-cn": "无法创建设备："
	},
	"Can not create channel: ": {
		"en": "Can not create channel: ",
		"de": "Kanal kann nicht erstellt werden:",
		"ru": "Не могу создать канал:",
		"pt": "Não é possível criar canal:",
		"nl": "Kan geen kanaal maken:",
		"fr": "Impossible de créer la chaîne :",
		"it": "Impossibile creare il canale:",
		"es": "No se puede crear el canal:",
		"pl": "Nie można utworzyć kanału:",
		"zh-cn": "无法创建频道："
	}
};

// @ts-ignore
if (typeof module !== 'undefined' && module.parent) {
	module.exports = _systemDictionary;
} else {
	systemDictionary = _systemDictionary;
}
